### ISSUE TITLE
Problem regarding authorization 

### ISSUE THREAD

**Issue by wolke42** [transmart/transmart-xnat-viewer#1]
@ricepeterm 
Here at the chair for Medical Informatics, we try to establish a connection between our own XNAT and tranSMART instance. Therefore, the transmart-xnat-viewer plugin should be used. The current situation is, that we have got the link "View Sessions" in tranSMART in the "Image View" Tab. But after clicking it, no information is retrieved. In the logs of tranSMART, there is a java.io.IOException because the XNAT server returned a HTTP response code 401 for the URL https://<xnat_ip>/data/projects/p02/subjects/XNAT_S00002/experiments?format=json .
The XNAT instance is protected by a username and password which are included in the Config.groovy. 

Our idea was, that this could be due to problems with the transmission of the login data for XNAT in the getAPIListData method in ScanController? Is that possible? Or are there other ideas on how to solve this problem?

Thanks in advance!

Best regards,
Judith Bauer

Chair of Medical Informatics
Friedrich-Alexander-University Erlangen-Nuremberg
91058 Erlangen-Tennenlohe

--------------------------------------
Exact error description:
`10-05-2017 12:29:39,161 ERROR GrailsExceptionResolver - IOException occurred when processing request: [GET] /transmart/Scan/getAPIListData
Server returned HTTP response code: 401 for URL: https://<xnat_ip>/data/projects/p02/subjects/XNAT_S00002/experiments?format=json. Stacktrace follows:
java.io.IOException: Server returned HTTP response code: 401 for URL: https://<xnat_ip>/data/projects/p02/subjects/XNAT_S00002/experiments?format=json
        at xnat.plugin.ScanController$_closure2.doCall(ScanController.groovy:21)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by ricepeterm** [comment]
Sorry, only just noticed this report. The URL that failed has "<xnat_ip>" as the address which should be the value of the org.xnat.domain parameter in Config.groovy. I suspect this value is missing or incorrectly specified.
